"""add_m4_analysis_models

Revision ID: 3f88aa8a120f
Revises: e6da2e749540
Create Date: 2026-07-26 16:31:24.459110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3f88aa8a120f'
down_revision: Union[str, None] = 'e6da2e749540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'category', name='uq_technology_name_category')
    )
    op.create_index(op.f('ix_technologies_id'), 'technologies', ['id'], unique=False)
    op.create_table('analysis_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('relative_path', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=32), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('lines_of_code', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('is_directory', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_files_analysis_id'), 'analysis_files', ['analysis_id'], unique=False)
    op.create_index('ix_analysis_files_analysis_path', 'analysis_files', ['analysis_id', 'relative_path'], unique=True)
    op.create_index('ix_analysis_files_extension', 'analysis_files', ['analysis_id', 'extension'], unique=False)
    op.create_index(op.f('ix_analysis_files_id'), 'analysis_files', ['id'], unique=False)
    op.create_table('analysis_technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.String(length=1024), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_technologies_analysis_id'), 'analysis_technologies', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_technologies_id'), 'analysis_technologies', ['id'], unique=False)
    op.create_table('dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('source_file', sa.String(length=1024), nullable=True),
    sa.Column('ecosystem', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependencies_analysis_id'), 'dependencies', ['analysis_id'], unique=False)
    op.create_index('ix_dependencies_ecosystem', 'dependencies', ['analysis_id', 'ecosystem'], unique=False)
    op.create_index(op.f('ix_dependencies_id'), 'dependencies', ['id'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_analysis_id'), 'metrics', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=False)
    op.create_index('ix_metrics_key', 'metrics', ['analysis_id', 'key'], unique=True)
    op.add_column('analyses', sa.Column('upload_id', sa.Integer(), nullable=False))
    op.add_column('analyses', sa.Column('error_detail', sa.String(length=1024), nullable=True))
    op.add_column('analyses', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.alter_column('analyses', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_analyses_upload_id'), 'analyses', ['upload_id'], unique=False)
    op.drop_constraint(op.f('analyses_project_id_fkey'), 'analyses', type_='foreignkey')
    op.create_foreign_key('fk_analyses_upload_id', 'analyses', 'uploads', ['upload_id'], ['id'])
    op.drop_column('analyses', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_analyses_upload_id', 'analyses', type_='foreignkey')
    op.create_foreign_key(op.f('analyses_project_id_fkey'), 'analyses', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_analyses_upload_id'), table_name='analyses')
    op.alter_column('analyses', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('analyses', 'completed_at')
    op.drop_column('analyses', 'error_detail')
    op.drop_column('analyses', 'upload_id')
    op.drop_index('ix_metrics_key', table_name='metrics')
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_analysis_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_dependencies_id'), table_name='dependencies')
    op.drop_index('ix_dependencies_ecosystem', table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_analysis_id'), table_name='dependencies')
    op.drop_table('dependencies')
    op.drop_index(op.f('ix_analysis_technologies_id'), table_name='analysis_technologies')
    op.drop_index(op.f('ix_analysis_technologies_analysis_id'), table_name='analysis_technologies')
    op.drop_table('analysis_technologies')
    op.drop_index(op.f('ix_analysis_files_id'), table_name='analysis_files')
    op.drop_index('ix_analysis_files_extension', table_name='analysis_files')
    op.drop_index('ix_analysis_files_analysis_path', table_name='analysis_files')
    op.drop_index(op.f('ix_analysis_files_analysis_id'), table_name='analysis_files')
    op.drop_table('analysis_files')
    op.drop_index(op.f('ix_technologies_id'), table_name='technologies')
    op.drop_table('technologies')
    # ### end Alembic commands ###
